version: '3.9'

services:

  app:
    build: .
    container_name: nest_api_container
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3333:3333
    networks:
      - freecodecamp

  db:
    container_name: postgres_container
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTEGRES_USER: postgres
      POSTGRES_PASSWORD: 132
      POSTGRES_DB: nest
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    networks:
      - freecodecamp

networks:
  freecodecamp:
    driver: bridge
