version: '3.9'

services:
  dev-db:
    container_name: postgres_container
    image: postgres:13
    ports:
      - 5434:5434
    environment:
      POSTEGRES_USER: postgres
      POSTGRES_PASSWORD: 132
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
