version: '3.9'

services:
  test-db:
    container_name: postgres_container_e2e
    image: postgres:13
    restart: always
    ports:
      - 5435:5432
    expose:
      - 5435
    environment:
      POSTEGRES_USER: postgres
      POSTGRES_PASSWORD: 132
      POSTGRES_DB: nest
    # volumes:
    #   - .docker/dbdata:/var/lib/postgresql/data
    networks:
      - freecodecamp

networks:
  freecodecamp:
    driver: bridge
